### PR TITLE
Remove redundant links

### PR DESCRIPTION
**Pull request by yitzhaks**
The download links for the Sysinternals Suite appear twice in this short
page. The ones at the end of the page seem to not be maintained (in
terms of updating the file sizes), so it seems most people see and use
the top set of links.
In light of the above, and in order to improve overall maintainability,
removing the set of links at the bottom of the page.

### CODE REVIEW

**Comment by v-kents** [comment]
OPS Build status updates of commit _[0d2799d](https://github.com/yitzhaks/sysinternals/pull/144/commits/0d2799d4632dd462b82fafa9563f6c838116b297)_: 

:clock10: **Preparing**: average preparing time is _40 sec(s)_

**Comment by v-kents** [comment]
OPS Build status updates of commit _[0d2799d](https://github.com/yitzhaks/sysinternals/pull/144/commits/0d2799d4632dd462b82fafa9563f6c838116b297)_: 

:clock10: **Incremental building**: average incremental building time is _20 sec(s)_

**Comment by v-kents** [comment]
OPS Build status updates of commit _[0d2799d](https://github.com/yitzhaks/sysinternals/pull/144/commits/0d2799d4632dd462b82fafa9563f6c838116b297)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sysinternals/downloads/sysinternals-suite.md](https://github.com/yitzhaks/sysinternals/blob/RemoveRedundentLinks/sysinternals/downloads/sysinternals-suite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sysinternals/downloads/sysinternals-suite?branch=pr-en-us-144) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C12%5C22%5C10c37dbd-f03d-3f2c-531a-9046ff809b23%5CPullRequest%5C201812221559497189-144%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=FRGSrWCOLhzadWNISPwT1eOR1RWLaHQcqBLpZ7vORRg%3D&st=2018-12-22T15%3A55%3A48Z&se=2019-01-22T16%3A00%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-kents** [comment]
OPS Build status updates of commit _[52766d9](https://github.com/yitzhaks/sysinternals/pull/144/commits/52766d9104ad5e52771e26748aca185e72ecd151)_: 

:clock10: **Preparing**: average preparing time is _45 sec(s)_

**Comment by yitzhaks** [comment]
@markrussinovich, can you please have a look at this?

**Comment by v-kents** [comment]
OPS Build status updates of commit _[52766d9](https://github.com/yitzhaks/sysinternals/pull/144/commits/52766d9104ad5e52771e26748aca185e72ecd151)_: 

:clock10: **Incremental building**: average incremental building time is _19 sec(s)_

**Comment by v-kents** [comment]
OPS Build status updates of commit _[52766d9](https://github.com/yitzhaks/sysinternals/pull/144/commits/52766d9104ad5e52771e26748aca185e72ecd151)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sysinternals/downloads/sysinternals-suite.md](https://github.com/yitzhaks/sysinternals/blob/RemoveRedundentLinks/sysinternals/downloads/sysinternals-suite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sysinternals/downloads/sysinternals-suite?branch=pr-en-us-144) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C5%5C10c37dbd-f03d-3f2c-531a-9046ff809b23%5CPullRequest%5C201903051850116338-144%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=3XVBUASIkybUOmQpCAiAa4xfmmyvaAiuzWIIM4nzKqE%3D&st=2019-03-05T18%3A46%3A18Z&se=2019-04-05T18%3A51%3A18Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-kents** [comment]
OPS Build status updates of commit _[8438bc4](https://github.com/yitzhaks/sysinternals/pull/144/commits/8438bc42aeb31bf0ef22e38ac88423fe6247c1b9)_: 

:clock10: **Preparing**: average preparing time is _45 sec(s)_

**Comment by v-kents** [comment]
OPS Build status updates of commit _[8438bc4](https://github.com/yitzhaks/sysinternals/pull/144/commits/8438bc42aeb31bf0ef22e38ac88423fe6247c1b9)_: 

:clock10: **Incremental building**: average incremental building time is _19 sec(s)_

**Comment by v-kents** [comment]
OPS Build status updates of commit _[8438bc4](https://github.com/yitzhaks/sysinternals/pull/144/commits/8438bc42aeb31bf0ef22e38ac88423fe6247c1b9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sysinternals/downloads/sysinternals-suite.md](https://github.com/yitzhaks/sysinternals/blob/RemoveRedundentLinks/sysinternals/downloads/sysinternals-suite.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sysinternals/downloads/sysinternals-suite?branch=pr-en-us-144) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C3%5C5%5C10c37dbd-f03d-3f2c-531a-9046ff809b23%5CPullRequest%5C201903051850449270-144%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=aGJLhlKYl1DTDYOa3VsTLZlB04mjP7a70ZGR6c6Dskk%3D&st=2019-03-05T18%3A47%3A26Z&se=2019-04-05T18%3A52%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
