### PR TITLE
junction.md: The long-needed update

### PR DESCRIPTION
**Pull request by skycommand**
The was missing critical information needed to use this tool. (Perhaps it was accidentally damaged?) I updated the page to supply the missing info.

### CODE REVIEW

**Comment by foxmsft** [comment]
Really appreciated! Gonna cross-reference with the source code and approve afterwards.

**Comment by skycommand** [comment]
@foxmsft You can see the source code? That might be useful. You see, there is another issue on this page that I can't fix myself: It uses "symbolic link" and "junction points" interchangeably, but they aren't the same thing. (Even if at some point in the past they were synonyms, they aren't now. For example, the documentation for [New-Item](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.management/new-item?view=powershell-7.1) treats them differently.)

If I am not mistaken, symbolic links are made with [CreateSymbolicLink()](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createsymboliclinkw), while hard links are made with [CreateHardLinkW()](https://docs.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createhardlinkw)

**Comment by foxmsft** [comment]
Haven't given much attention to `junction` lately. There's a good chance it's a bit behind times. I'll track this one and make changes in the tool as well, if required.

**Review by foxmsft — APPROVED** [review]
Good catch, thank you!

**Review by foxmsft — APPROVED** [review]

**Pull request merged**
