### PR TITLE
Policheck Update - Oct 12 | Bulk Update

### PR DESCRIPTION
**Pull request by damabe**
Fixes the following Policheck issue:

https://dev.azure.com/msft-skilling/learn-platform-policheck/_workitems/edit/102879

### CODE REVIEW

**Comment by MeeraDi** [comment]
@MicrosoftDocs/windows-repo-admins 
This PR fixes a potentially sensitive term that was identified by Policheck. Please approve this bulk PR.

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by MeeraDi** [comment]
#sign-off

**Review by Karl-Bridge-Microsoft — APPROVED** [review]

**Comment by damabe** [comment]
#sign-off

**Review by foxmsft — APPROVED** [review]
Thanks!

**Pull request merged**
