### PR TITLE
Update notmyfault.md

### PR DESCRIPTION
**Pull request by jeffstokes72**
removed a random 'o' character

### CODE REVIEW

**Comment by v-kents** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sysinternals/downloads/notmyfault.md](https://github.com/jeffstokes72/sysinternals/blob/patch-1/sysinternals/downloads/notmyfault.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sysinternals/downloads/notmyfault?branch=pr-en-us-104) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C7%5C16%5C10c37dbd-f03d-3f2c-531a-9046ff809b23%5CPullRequest%5C201807162136060045-104%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ECZCY6abJ3CP64WitI1IzWrmXTHlpzmJZjrRzALNVm4%3D&st=2018-07-16T21%3A32%3A03Z&se=2018-08-16T21%3A37%3A03Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by jeffstokes72** [comment]
Hello, this has been pending for 2 weeks, you still have the typo fyi.

**Comment by jeffstokes72** [comment]
I get it's not a huge deal just surprised to see it open this long :)

**Comment by v-kents** [comment]
@jeffstokes72 Sorry about that - since the product team took managing the site back, I assumed they'd approve it. Done.

**Pull request merged**
