### PR TITLE
fixing links

### PR DESCRIPTION
**Pull request by jdelauri**

### CODE REVIEW

**Review by jdelauri — COMMENTED** [review]
making absolute links

**Review by jdelauri — COMMENTED** [review]
fixing absolute link

**Review by jdelauri — COMMENTED** [review]
fixing relative links

**Review by jdelauri — COMMENTED** [review]
Fixing absolute links

**Review by jdelauri — COMMENTED** [review]
fixing absolute link

**Comment by jdelauri** [comment]
Hi @foxmsft the Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. 

Are you able to review and merge this PR? If not, can refer someone who can? Thanks.

**Review by foxmsft — COMMENTED** [review]
What is the deal with the `https://shows/defrag-tools` links? Are they meant as placeholders or as relative links?

**Comment by jdelauri** [comment]
> What is the deal with the `https://shows/defrag-tools` links? Are they meant as placeholders or as relative links?

@foxmsft  Github came back with warnings that said to remove the **docs.microsoft.com/en-us** part of those links. Here's one in the original state:  https://docs.microsoft.com/en-us/shows/defrag-tools/2-process-explorer  

I'll present this in my team meeting today and we'll get it right.

**Review by jdelauri — COMMENTED** [review]
fixing mistake on relative links

**Review by jdelauri — COMMENTED** [review]
Fixing mistake in relative link

**Review by jdelauri — COMMENTED** [review]
Fixing mistake in relative links

**Comment by jdelauri** [comment]
@foxmsft relative links are fixed. They should now look like this:  /shows/defrag-tools/2-process-explorer 

This is ready for review, thanks.

**Review by foxmsft — APPROVED** [review]
Thanks!

**Pull request merged**
