### PR TITLE
Remove erroneous right square bracket after download link

### PR DESCRIPTION
**Pull request by cavaliersa**

### CODE REVIEW

**Comment by v-kents** [comment]
OPS Build status updates of commit _[460d249](https://github.com/cavaliersa/sysinternals/pull/152/commits/460d2496f408e2db921ead65283ec9aa047f9093)_: 

:clock10: **Preparing**: average preparing time is _46 sec(s)_

**Comment by v-kents** [comment]
OPS Build status updates of commit _[460d249](https://github.com/cavaliersa/sysinternals/pull/152/commits/460d2496f408e2db921ead65283ec9aa047f9093)_: 

:clock10: **Full build**: average full build time is _21 sec(s)_ [calculated from last _3_ build(s)]

> Note: A full build takes more time than an incremental build.  This is the expected behavior of the build system.

**Comment by v-kents** [comment]
OPS Build status updates of commit _[460d249](https://github.com/cavaliersa/sysinternals/pull/152/commits/460d2496f408e2db921ead65283ec9aa047f9093)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sysinternals/downloads/bginfo.md](https://github.com/cavaliersa/sysinternals/blob/patch-1/sysinternals/downloads/bginfo.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sysinternals/downloads/bginfo?branch=pr-en-us-152) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C15%5C10c37dbd-f03d-3f2c-531a-9046ff809b23%5CPullRequest%5C201902151410415622-152%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Faarl4pWpXngw%2FJ4wDfvP3Pz4qfJGbMdjYJIfN%2BH5x4%3D&st=2019-02-15T14%3A07%3A24Z&se=2019-03-18T14%3A12%3A24Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lukekim** [comment]
This was fixed by another PR.

**Pull request closed without merging**
