### PR TITLE
updates for v9.10

### PR DESCRIPTION
**Pull request by olafhartong**
added; 
- the DNS event 
- all event types
- the accepteula to usage
updated the version number

### CODE REVIEW

**Comment by v-kents** [comment]
Docs Build status updates of commit _[0a6edda](https://github.com/olafhartong/sysinternals/pull/192/commits/0a6edda6c4f3ea81ba8d85868d1d32eb7c4db768)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[bread/toc.json](https://github.com/olafhartong/sysinternals/blob/master/bread/toc.json) | :warning:Warning | | [Details](#user-content-c7daa6b9-95927e00)
[toc.json](https://github.com/olafhartong/sysinternals/blob/master/toc.json) | :warning:Warning | | [Details](#user-content-2cac9234-95927e00)
[sysinternals/downloads/sysmon.md](https://github.com/olafhartong/sysinternals/blob/master/sysinternals/downloads/sysmon.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sysinternals/downloads/sysmon?branch=pr-en-us-192) |

<a id="c7daa6b9-95927e00"></a>
### [bread/toc.json](https://github.com/olafhartong/sysinternals/blob/master/bread/toc.json)
 - **[Warning]** `````Error happen when converting bread/toc.json to Pdf. Details: Could not find a part of the path 'T:\cvri\bread\toc.json'.`````

<a id="2cac9234-95927e00"></a>
### [toc.json](https://github.com/olafhartong/sysinternals/blob/master/toc.json)
 - **[Warning]** `````Error happen when converting toc.json to Pdf. Details: Could not find file 'T:\cvri\toc.json'.`````

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C6%5C10%5C10c37dbd-f03d-3f2c-531a-9046ff809b23%5CPullRequest%5C201906101240322774-192%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=DWqySVK8EgTmBWyeqdB1gI9qZHdZwCgdLSGJ9lXgzWk%3D&st=2019-06-10T12%3A37%3A02Z&se=2019-07-11T12%3A42%3A02Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by olafhartong** [comment]
I do not have access to these files, not do I have them ;)

**Comment by olafhartong** [comment]
this release is also dependant on Mark's publication of version 9.10 tomorrow

**Comment by lukekim** [comment]
Thanks for this Olaf. We've now published 10.0 so closing this PR. If there are additional update you want to make against the new version please create a new PR.

**Pull request closed without merging**
