### PR TITLE
Update sysmon.md

### PR DESCRIPTION
**Pull request by jeffstokes72**
adjusted version, date. Reflecting version 6.03 that was released June 17th 2017

### CODE REVIEW

**Comment by v-kents** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sysinternals/downloads/sysmon.md](https://github.com/jeffstokes72/sysinternals/blob/patch-1/sysinternals/downloads/sysmon.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sysinternals/downloads/sysmon?branch=pr-en-us-10) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C7%5C10c37dbd-f03d-3f2c-531a-9046ff809b23%5CPullRequest%5C201709070321073904-10%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-kents** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sysinternals/downloads/sysmon.md](https://github.com/jeffstokes72/sysinternals/blob/patch-1/sysinternals/downloads/sysmon.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sysinternals/downloads/sysmon?branch=pr-en-us-10) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C8%5C10c37dbd-f03d-3f2c-531a-9046ff809b23%5CPullRequest%5C201709080550532114-10%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-kents** [comment]
### :x: Validation status: errors


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-)

<a name=""></a>
### []()
 - **[Error]** Manifest json file &#39;.manifest.json&#39; is invalid. Details: Value cannot be null.
Parameter name: pathUnderSubfolder

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2017%5C9%5C11%5C10c37dbd-f03d-3f2c-531a-9046ff809b23%5CPullRequest%5C201709110327365728-10%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lukekim** [comment]
This is now redundant

**Comment by jeffstokes72** [comment]
you're welcome i guess

**Pull request closed without merging**
