### PR TITLE
typo: Double word "to"

### PR DESCRIPTION
**Pull request by dpisanu**
Cleaning up the typo double use of 'to'

### CODE REVIEW

**Comment by dpisanu** [comment]
my pleasure :)

**Comment by mairaw** [comment]
You might need to close and reopen to trigger a new build.

**Comment by v-kents** [comment]
Docs Build status updates of commit _[e7679f2](https://github.com/dpisanu/sysinternals/pull/120/commits/e7679f2d3b19543a2ef933c33927a801b280464c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sysinternals/learn/troubleshooting-book.md](https://github.com/dpisanu/sysinternals/blob/typo_double.use_to/sysinternals/learn/troubleshooting-book.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sysinternals/learn/troubleshooting-book?branch=pr-en-us-120) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C22%5C10c37dbd-f03d-3f2c-531a-9046ff809b23%5CPullRequest%5C201904221640476814-120%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=hUlN7T6SYxo27STnhYR2iYizR6c06SMWIU7eCFhEalM%3D&st=2019-04-22T16%3A37%3A07Z&se=2019-05-23T16%3A42%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-kents** [comment]
Docs Build status updates of commit _[222c4bd](https://github.com/dpisanu/sysinternals/pull/120/commits/222c4bd11a8aa0cbdd7538b6f7fdbe71b19170e9)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sysinternals/learn/troubleshooting-book.md](https://github.com/dpisanu/sysinternals/blob/typo_double.use_to/sysinternals/learn/troubleshooting-book.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sysinternals/learn/troubleshooting-book?branch=pr-en-us-120) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C22%5C10c37dbd-f03d-3f2c-531a-9046ff809b23%5CPullRequest%5C201904221641504497-120%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=oKoeign6Js1VQPh9m2S0l1xjLkO6i7U2lPzroqYnkFQ%3D&st=2019-04-22T16%3A38%3A37Z&se=2019-05-23T16%3A43%3A37Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request merged**
