### PR TITLE
Fix list formatting

### PR DESCRIPTION
**Pull request by ChrisMaddock**
https://docs.microsoft.com/en-gb/sysinternals/downloads/vmmap

Formatting is broken in the related links section

### CODE REVIEW

**Comment by v-kents** [comment]
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sysinternals/downloads/vmmap.md](https://github.com/ChrisMaddock/sysinternals/blob/patch-1/sysinternals/downloads/vmmap.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sysinternals/downloads/vmmap?branch=pr-en-us-80) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C5%5C3%5C10c37dbd-f03d-3f2c-531a-9046ff809b23%5CPullRequest%5C201805031247229181-80%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=vbPWBtwK%2FzXIa5%2FeX0TbcnccuRyPgDHSsVqcHsWNU3U%3D&st=2018-05-03T12%3A43%3A21Z&se=2018-06-03T12%3A48%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lukekim** [comment]
Please re-create this PR to target `master`

**Comment by ChrisMaddock** [comment]
Hi @lukekim 

If these PR's should target master, then I think this repo may be set up incorrectly - I just followed the 'Edit' button on the side of the docs.microsoft.com page, which directs me to submit my PR against live. 

This doesn't appear to be the case for other Microsoft docs repos I've contributed to.

image

I'll recreate my changes now.

**Comment by ChrisMaddock** [comment]
I should clarify - my process was following the 'Edit' button on the side of the docs page, and then editing the content in the GitHub interface. This is my normal process for minor corrections.

**Comment by lukekim** [comment]
Thanks for the note. `master` is set as the default branch for the repository. Not sure how to fix the default PR branch, any ideas?

**Comment by ChrisMaddock** [comment]
@lukekim Aha! Looks like I mis-diagnosed. 

The edit link on the side of the pages is this: https://github.com/MicrosoftDocs/sysinternals/blob/live/sysinternals/downloads/vmmap.md

Note that that link directly targets the `live` branch - sounds like it shouldn't do! In `dotnet/docs`, the edit link target's `master`.

**Pull request closed without merging**
