### PR TITLE
Update Sysinternals forum link

### PR DESCRIPTION
**Pull request by MichaelPolla**
It's my first pull request ever, so I hope I did well :blush:

### CODE REVIEW

**Comment by v-kents** [comment]
OPS Build status updates of commit _[a95ac16](https://github.com/MichaelPolla/sysinternals/pull/151/commits/a95ac1647623656ef41363700472d89f1264eb85)_: 

:clock10: **Preparing**: average preparing time is _42 sec(s)_

**Comment by v-kents** [comment]
OPS Build status updates of commit _[a95ac16](https://github.com/MichaelPolla/sysinternals/pull/151/commits/a95ac1647623656ef41363700472d89f1264eb85)_: 

:clock10: **Incremental building**: average incremental building time is _20 sec(s)_

**Comment by v-kents** [comment]
OPS Build status updates of commit _[a95ac16](https://github.com/MichaelPolla/sysinternals/pull/151/commits/a95ac1647623656ef41363700472d89f1264eb85)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sysinternals/index.md](https://github.com/MichaelPolla/sysinternals/blob/patch-1/sysinternals/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sysinternals/index?branch=pr-en-us-151) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C2%5C12%5C10c37dbd-f03d-3f2c-531a-9046ff809b23%5CPullRequest%5C201902120730459899-151%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=TpjwWQXTRqRRfoT%2BfLbYBUw1byC80%2B9HkJ%2Fvqc5o7Rs%3D&st=2019-02-12T07%3A27%3A23Z&se=2019-03-15T07%3A32%3A23Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-kents** [comment]
Docs Build status updates of commit _[892f4d8](https://github.com/MichaelPolla/sysinternals/pull/151/commits/892f4d8bab6b5c30b144e8bc3d05a681b969fb6d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[sysinternals/index.md](https://github.com/MichaelPolla/sysinternals/blob/patch-1/sysinternals/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/sysinternals/index?branch=pr-en-us-151) |

For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2019%5C4%5C22%5C10c37dbd-f03d-3f2c-531a-9046ff809b23%5CPullRequest%5C201904221631269278-151%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=2VmaknSCTTWquY%2FTYGK9GclwL0tyjWJGW8r7jEsn3TA%3D&st=2019-04-22T16%3A27%3A46Z&se=2019-05-23T16%3A32%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by lukekim** [comment]
Thanks!

**Pull request merged**
