### PR TITLE
[BrokenLinksH2] Fix path in link

### PR DESCRIPTION
**Pull request by DhurataJ**
support link no longer exists

### CODE REVIEW

**Comment by DhurataJ** [comment]
**Global effort to fix broken links**

@foxmsft - The Content & Learning team is fixing broken links on docs.microsoft.com for the rest of H2. This effort will eliminate potential accessibility, security, and usability issues. This PR includes only link fixes and does not change other content. I'd very much appreciate your timely review and feedback on the link changes I've suggested. Thanks!

**Review by foxmsft — COMMENTED** [review]
I wanted to keep the broken link as text-only, so that people researching this historic info can eventually reach the source on the Internet Archive or similar websites.

**Comment by foxmsft** [comment]
I'm keeping the broken url in this case, as the old plaintext and not a hyperlink.

**Comment by foxmsft** [comment]
Closing this one, as I want to keep the "broken" link as text-only on the page.

**Pull request closed without merging**
